### ISSUE TITLE
2012r2's firewall blocks RDP

### ISSUE THREAD

**Issue by hunner** [ferventcoder/vagrant-windows-puppet#11]
After doing a `vagrant up` using the below configuration, the two networks attached are NAT and Host networks. They are both considered to be public networks by the windows network manager.

RDP works when the networks (or even just the NAT network) is changed to the private network profile. This can be done via powershell using `Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private`

Vagrant config:
```ruby
Vagrant.configure("2") do |c|
  c.ssh.insert_key = false
  c.vm.define 'win2012r2-x64' do |v|
    v.vm.box = 'ferventcoder/win2012r2-x64-nocm'
    v.vm.box_check_update = 'true'
    v.vm.communicator = "winrm"
    v.vm.network :private_network, ip: "10.255.67.217", :netmask => "255.255.0.0", :mac => "080027AEC176"
    v.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh', auto_correct: true
    v.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
    v.vm.network :forwarded_port, guest: 5985, host: 5985, id: 'winrm', auto_correct: true
    v.vm.guest = :windows
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024', '--cpus', '1']
    end
  end
end
```

**Comment by hunner** [comment]
Relatedly, http://superuser.com/a/837051 indicates the same problem (that windows will use the public network profile when it has dynamically created virtualbox interfaces and that blocks services like RDP).

**Comment by ferventcoder** [comment]
I prefer to have the windows firewall completely shut off for a vagrant vm, but winrm doesn't like it.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by hunner** [comment]
Adding just a simple provisioning step into the Vagrantfile helps with this too; is there a way to have provisioners built-in to the box?
```ruby
v.vm.provision "shell", inline: "Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private"
```

**Comment by ferventcoder** [comment]
With vagrant? Unsure.

**Comment by hunner** [comment]
Looks like no: https://stackoverflow.com/questions/28704152/vagrant-provision-using-files-included-in-box-from-packer

**Comment by ferventcoder** [comment]
closing as stale.
