### ISSUE TITLE
Puppet set PATH not working and fail puppet calls later

### ISSUE THREAD

**Issue by iDVB** [ferventcoder/vagrant-windows-puppet#6]
When running `vagrant up` for `win7x64pro-vagrant` it seems to run almost flawlessly until it trys to make puppet calls.

It's failing because the PATH vars are not being set. Which errors with ... "The term 'puppet' is not recognized as the name of a cmdlet"
![Puppet PATH not set](http://goo.gl/F6Jx4Z)

When Manually setting the path in the VM and then manually calling `puppet` I can then see that the path is correctly set.

Is there a chance these scripts could be broken somewhere, or am I doing something wrong?

```
Virtualbox: 4.3.26
Vagrant: 1.7.2
Host: OSX 10.10.3
```

UPDATE - Only other thing I can think of is that maybe the windows licensing prompt is crapping out the scripts? I intend to license only IF I can actually get this to work.

**Comment by ferventcoder** [comment]
Are you using my windows 7 box? I lited it, but it should work for this scenario. Did puppet get installed? From what I see here it looks like other things are missing?

**Comment by ferventcoder** [comment]
I haven't looked at the windows 7 vagrantfile in awhile, it could be that it needs some updates.

**Comment by ferventcoder** [comment]
I see you commented here https://github.com/WinRb/vagrant-windows/issues/101 first.

**Comment by iDVB** [comment]
I thought I found the issue. But it did **not** fix this. 

It seems that `main.cmd` is using `SET PATH` to put puppet in the env vars.  However, it appears that `SET PATH` vars are lost by the time the rest of the puppet scripts are run. After a bit of googling, I [found](http://www.windows-commandline.com/set-path-command-line/) that `SETX PATH` is the permanent alternative to `SET PATH` with only works during the life of that console session.


The only other observation is that even though the env vars are being permanently set in CMD, when opening the PowerShell Prompt and typing `puppet` It errors out with the same as above. Maybe all this is running in PShell context and it does not have that PATH?

**Comment by iDVB** [comment]
Sorry.... yes this is 100% all your code. I did not change anything and I'm getting this error.You can see in the screenshot that I'm running `vagrant up` directly from within your directory. Even made sure to add those `puppet/modules` and `puppet/box_modules` folders and such.

**Comment by iDVB** [comment]
Wow..... weird. When I used `SETX PATH` manually in the VM, I could close and open new cmd windows and the PATH would persist. However, putting that same code into `main.cmd` and then `vagrant destroy` and then `vagrant up`, does not work... same error. Then I manually log into VM again and when I drop to CMD the PATH var is still not set?!!?!

![SETX PATH](http://goo.gl/y0BXUE)

**Comment by ferventcoder** [comment]
So the Puppet install itself will set the path permanently.

**Comment by ferventcoder** [comment]
But it doesn't update the current path, that's why we use `SET`.

**Comment by ferventcoder** [comment]
As far as that Windows 7 box, I would recommend against using it if you find it has issues. Like I said, it was lited, so things may not work correctly.

**Comment by ferventcoder** [comment]
You can try the 2008 box and see if it also has the same issues. It is used more regularly so...

**Comment by iDVB** [comment]
Done. Used the `win2008r2x64-vagrant` this time.
However, seems like the exact same issue.

Looks the the CertUtil is also erring out with "DecodeFile returned The system cannot find the file specified"

```
==> default: Puppet successfully installed.
==> default:
==> default:
==> default: C:\Windows\system32>certutil -v -addstore Root "c:\vagrantshared\resources\certs\geotrust.global.pem"
==> default: Root
==> default: DecodeFile returned The system cannot find the file specified. 0x80070002 (WIN32: 2)
==> default: CertUtil: -addstore command FAILED: 0x80070002 (WIN32: 2)
==> default: CertUtil: The system cannot find the file specified.
==> default:
==> default: C:\Windows\system32>certutil -v -addstore Root "c:\vagrantshared\resources\certs\usertrust.network.pem"
==> default: Root
==> default: DecodeFile returned The system cannot find the file specified. 0x80070002 (WIN32: 2)
==> default: CertUtil: -addstore command FAILED: 0x80070002 (WIN32: 2)
==> default: CertUtil: The system cannot find the file specified.
==> default:
==> default: C:\Windows\system32>SET PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\Puppet\bin;
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: #< CLIXML
==> default: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
<S S="Error">The term 'puppet' is not recognized as the name of a cmdlet, function, script f_x000D__x000A_</S>
<S S="Error">ile, or operable program. Check the spelling of the name, or if a path was incl_x000D__x000A_</S>
<S S="Error">uded, verify that the path is correct and try again._x000D__x000A_</S>
<S S="Error">At line:1 char:136_x000D__x000A_</S>
<S S="Error">+ $env:FACTER_domain='local'; $env:FACTER_kernel='windows'; $env:FACTER_operati_x000D__x000A_</S>
<S S="Error">ngsystem='windows'; $env:FACTER_osfamily='windows'; puppet &lt;&lt;&lt;&lt;  apply --debug _x000D__x000A_</S>
<S S="Error">--trace --verbose --modulepath '/tmp/vagrant-puppet/modules-564e5a9348d0d575048_x000D__x000A_</S>
<S S="Error">ffd2ba56834a2;/ProgramData/PuppetLabs/puppet/etc/modules' --manifestdir /tmp/va_x000D__x000A_</S>
<S S="Error">grant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 --detailed-exitcodes /t_x000D__x000A_</S>
<S S="Error">mp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/site.pp; exit $LAS_x000D__x000A_</S>
<S S="Error">TEXITCODE_x000D__x000A_</S>
<S S="Error">    + CategoryInfo          : ObjectNotFound: (puppet:String) [], CommandNotFo _x000D__x000A_</S>
<S S="Error">   undException_x000D__x000A_</S>
<S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S>
<S S="Error"> _x000D__x000A_</S></Objs>
```

**Comment by iDVB** [comment]
Just to be completely open, my first go with Vagrant in general has been with Windows (after hearing nothing but praises w *nix) but so far, I've run into nothing but issues with Windows+Vagrant. I really have no choice though as our environments are Windows, so gotta keep on chug'n. 

Really hope someone can suggest a fix for this or an alternative direction.

**Comment by ferventcoder** [comment]
Sooo, I can tell you that what you are seeing is not typical of my or others experience. There seems to be something interesting going on with your install. You may want to give vagrant 1.6.5 a shot. I don't have issues with that version and I typically wait for a .3 .z release before upgrading to a new major/minor - so I'm waiting on 1.7.3 still.

**Comment by ferventcoder** [comment]
I don't know if that makes you feel better or worse. I can't repro what you are seeing. It could be something with 1.7.2 but it seems like it is an issue finding files, which tells me something is weird about your environment. 

Let's start from the beginning -

1. Where are you running vagrant up from? Exact directory pls.
1. Vagrant plugin list (should NOT have vagrant-windows, that plugin is only necessary pre vagrant 1.6)
1. Vagrant box list
1. Virtualbox provider I assume? Virtualbox is another one to be careful which release you get. I'll need to check which version I am on.

**Comment by iDVB** [comment]
1. Directory:
     - ~/Projects/vagranttests/boxes/win2008r2x64-vagrant/
1. Vagrant Plugins:
     - vagrant-share (1.1.3, system)
1. Vagrant Boxes:
     - ie9_win7_base (virtualbox, 0)  (this is one of mine)
     - win2008r2x64  (virtualbox, 0)
     - win7x64pro    (virtualbox, 0)
1. Virtualbox 4.3.26

Going to try uninstalling and reinstalling v1.6.5 Vagrant

**Comment by ferventcoder** [comment]
All of that looks fine.

**Comment by ferventcoder** [comment]
https://github.com/mitchellh/vagrant/issues/5806 - not sure if it related

**Comment by iDVB** [comment]
All the same errors, even with Vagrant 1.6.5 (after uninstalling 1.7.2)

```
==> default: DecodeFile returned The system cannot find the file specified. 0x80070002 (WIN32: 2)
==> default: CertUtil: -addstore command FAILED: 0x80070002 (WIN32: 2)
==> default: CertUtil: The system cannot find the file specified.
```
and
```
The term 'puppet' is not recognized as the name of a cmdlet, function, script
```

Just a recap of my HOST setup...
```
Virtualbox: 4.3.26
Vagrant: 1.6.5
Host: OSX 10.10.3
```

Also, not sure if its normal, but I noticed all of these end up running the VM GUI where as I'll my personal tested prior to this ran things headless. Also the Docs talk about that being the default as well?

**Comment by ferventcoder** [comment]
Vagrant plugin list should have a bunch more items in it now.

**Comment by ferventcoder** [comment]
Or at least 
* vagrant-login
* vagrant-share

**Comment by iDVB** [comment]
yup... only those two.

**Comment by ferventcoder** [comment]
Sweet. I just pushed the certs up, so you should be able to grab latest and have those.

**Comment by iDVB** [comment]
You thinking that might make a difference?

**Comment by ferventcoder** [comment]
that will get the certs up for you so it finds them

**Comment by ferventcoder** [comment]
> Also, not sure if its normal, but I noticed all of these end up running the VM GUI where as I'll my personal tested prior to this ran things headless. Also the Docs talk about that being the default as well?

This is set up to be the default in https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/VagrantWindows.rb#L8

**Comment by ferventcoder** [comment]
Can you do the following? 
`VAGRANT_LOG=DEBUG vagrant up` and post that to a gist, then link that here?

**Comment by iDVB** [comment]
Sure. on it now.

**Comment by iDVB** [comment]
bump?

**Comment by ferventcoder** [comment]
Oh - github doesn't tell you in notifications if you update a comment

**Comment by ferventcoder** [comment]
You can redirect stdout/stderr to a file

**Comment by ferventcoder** [comment]
Perhaps isolate down just to ensure that puppet is installing correctly?

**Comment by ferventcoder** [comment]
Isolate down the vagrantfile to ensure that the only shell provisioner running is the only installing puppet

**Comment by iDVB** [comment]
Does this have anything to do with this?  https://tickets.puppetlabs.com/browse/PUP-3471 seems like the same issue, however, it appears your scripts are installing the 64bit version of puppet... no? 
`default: Installing Puppet. Running msiexec.exe /qn /norestart /i c:\vagrantshared\resources\installers\puppet-agent-x64.msi`

**Comment by iDVB** [comment]
I updated the gist with the FULL shell output from the `vagrant up` (using stdout - thank for that)
https://gist.github.com/iDVB/957c4e98cfd0a2023c95

Any thoughts?

**Comment by iDVB** [comment]
Oh, and Puppet IS getting installed. It's just the PATH seems to only be set in GUI env vars and not the cmd? (I thought this was the same?) 
![PATH vars](http://goo.gl/Km9DLS)

Here is the paste from the GUI env vars PATH...
```
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;c:\Program Files\Puppet Labs\Puppet\bin
```

**Comment by ferventcoder** [comment]
Sometimes I've seen that even though it is in the System PATH, it refuses to be there in the shell, even if you restart the shell numerous times. the only thing that seems to make it work is to reboot the box (vagrant reload) and things start working. It's the weirdest thing where path is no longer updating.

**Comment by iDVB** [comment]
what about `SETX PATH` or these lines in the `main.cmd`
```
echo "Ensuring environment for puppet - this puts the puppet ruby on the path for librarian"
call environment.bat
SET FACTER_domain=local
```

**Comment by ferventcoder** [comment]
So how old is your main.cmd? 

https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/shared/shell/main.cmd#L39-L49

**Comment by ferventcoder** [comment]
Lots of looking into this, http://serverfault.com/a/8856/79259 seems to lead you down the correct path. For whatever reason, explorer.exe is not being notified of the updates, so any new app you start will still have the older environment variables. 

However, based on https://support.microsoft.com/en-us/kb/104011 it appears sometimes updates to environments don't make it out, so one can do this so explorer learns of the updates

```c++
 SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, 0,
    (LPARAM) "Environment", SMTO_ABORTIFHUNG,
    5000, &dwReturnValue);
```

And we can do that in powershell with http://poshcode.org/2049: 

```powershell
if (-not ("win32.nativemethods" -as [type])) {
    # import sendmessagetimeout from win32
    add-type -Namespace Win32 -Name NativeMethods -MemberDefinition @"
[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(
    IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam,
    uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
"@
}

$HWND_BROADCAST = [intptr]0xffff;
$WM_SETTINGCHANGE = 0x1a;
$result = [uintptr]::zero

# notify all windows of environment block change
[win32.nativemethods]::SendMessageTimeout($HWND_BROADCAST, $WM_SETTINGCHANGE,  [uintptr]::Zero, "Environment", 2, 5000, [ref]$result);
```

If you want to add that somewhere after puppet is installed in one of the ps1 files and let me know if any new processes like cmd you start up on the box are good to go, I'd appreciate that and we can move forward with a fix.

**Comment by iDVB** [comment]
Thanks @ferventcoder ! I just tried this out at the bottom of `InstallPuppetFromMSI.ps1` just before the `Write-Host "Puppet successfully installed."` and still seems to output the same error.

This is where I openly admit that I'm usually more of a *nix guy and can really only scrape by with PowerShell. 

However, here is what I did...
https://gist.github.com/iDVB/9ee53de53bdcb31a37b9

...added that Write-Host `"Notifing processes of PATH Change"` so you can see that it ran in the log...
which it is consoling out. I also see that it's consoling out ` ==> default: 1 `
https://gist.github.com/iDVB/957c4e98cfd0a2023c95#file-gistfile1-sh-L136

...which from the comments... `# A non-zero result from SendMessageTimeout indicates success.`

So now I'm set to start the tears. :cry:

**Comment by iDVB** [comment]
Thoughts? Does my edits look proper? I'm really not sure how to test this

**Comment by iDVB** [comment]
Tested manually during RDP into VM and in PS prompt when running `puppet` it looks like the PATH is not set. 

Then I manually run that broadcast script above, and then rerun `puppet` command and it still looks like the PATH is not set.

BUT.... I then CLOSE the PowerShell window after having just ran that broadcast script above and then reopen and run `puppet` and NOW it looks like it worked. :(

No idea WTF.

**Comment by ferventcoder** [comment]
Sounds like it worked - you always have to close and reopen your shell to get environment updates - there is no automatic update to shells - no `. ~/.profile` either.

But if you are not having to restart explorer/logout/reboot, it sounds like it worked.

**Comment by iDVB** [comment]
Well it worked "the second time" However, thats because I'm manually restarting PowerShell. 
However, each time I run `vagrant destroy` then `vagrant up` it always errors out since its the first time its being run.

**Comment by ferventcoder** [comment]
For some reason though it isn't working in the shell provisioner. :/

**Comment by ferventcoder** [comment]
Perhaps the answer in the shell provisioner is to force a reload of explorer by killing and restarting explorer to guarantee it gets updated.

**Comment by iDVB** [comment]
Isn't installing Puppet on Windows for Vagrant something that is "old hat" by now? I'm totally new to vagrant and just surprised at how flawed/immature the Windows experience is with it. I would have thought just getting a basic vagrant box with puppet on it would be a piece of cake? Seems like it is only a few lines of code with Unix.

**Comment by ferventcoder** [comment]
Again - your experience isn't typical. 

Puppet has no issues installing on Windows and setting PATH.

Your issues are likely related to Windows and your version of VirtualBox.

**Comment by ferventcoder** [comment]
Windows is fundamentally different than Linux. In the past it has favored GUI-driven tasks where Linux has favored CLI-based tasks. It goes without saying which one is easier to automate.

**Comment by iDVB** [comment]
But you are using the exact same version of everything as me, no? (including virtualbox)

I thought the whole idea of Vagrant was it was supposed to fix the "It works on my box" thing. :smile:

**Comment by iDVB** [comment]
Ok here is something interesting. When manually run `$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")` ([from here](http://stackoverflow.com/questions/17794507/reload-the-path-in-powershell)) in PowerShell and then run `puppet` it WORKS! but.... when I close puppet and reopen and run `puppet` it does not work. (lost Path)

BUT! If run *both* the above broadcast script into and then this above `$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")` script in PowerShell and then run `puppet` it WORKS and closing and reopening PowerShell and running `puppet` again WORKS TO!

However, and he's the really sad part. Putting these at the bottom of `InstallPuppetFromMSI.ps1' and then `vagrant destroy` and `vagrant up` does not work. Same error as always.

**Comment by ferventcoder** [comment]
Sounds like a vagrant issue then. When you uninstalled the newer version and installled the older version, did you actually run the uninstall script for vagrant between them or just run the new dmg file over the other?

**Comment by ferventcoder** [comment]
We are already updating the path. The issue doesn't seem like that is the problem.

**Comment by iDVB** [comment]
Nope, did not run uninstall. Trying again now with the uninstall...

**Comment by iDVB** [comment]
Just tried using the uninstall script, rebooting, and then reinstalling vagrant 1.6.5
Still same error.

D

**Comment by ferventcoder** [comment]
Earlier you stated we have the same virtualbox, but I'm still on an older version of vbox. 4.2.16 I believe.

**Comment by ferventcoder** [comment]
4.3.12, just checked.

**Comment by iDVB** [comment]
Sigh.... even tried that too. Still no luck. Same exact error.  I'm up for trying anything!

![Still no dice](http://goo.gl/buElSJ)

Maybe now is a good time to start assuming I'm doing something stupid?

**Comment by iDVB** [comment]
I also noticed something that doesn't look right to me.

1.  the `Vagrantfile` have code in it that references a `puppet v3.2.1`. https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/win2008r2x64-vagrant/Vagrantfile#L47
1.  the `InstallPuppetFromMSI.ps1` then has a reference to installing `puppet v3.8.1`  https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/shared/shell/InstallPuppetFromMSI.ps1#L1
1. ...And then the `site.pp` file looks like its trying to enforce specifically `puppet v3.4.3` 

Am I missing something, or does that seem odd?

**Comment by ferventcoder** [comment]
You figured the version difference is in whether installing PE or not.
I can test from a completely new clone.

**Comment by iDVB** [comment]
Any luck? Things still work the same, even when starting from brand new clone?

**Comment by ferventcoder** [comment]
With a brand new clone I see this issue.

**Comment by ferventcoder** [comment]
If I do a `vagrant reload` followed by `vagrant provision`, things move forward without any more issues. 

Perhaps there is something that can be done to fix this moving forward, but right now I think we've exhausted most of what I know to do short of getting on the vm and doing the message.

**Comment by ferventcoder** [comment]
I added tskill but it doesn't seem to have an effect. The one boon is I immediately can do `puppet` on the command line in the box though.

**Comment by iDVB** [comment]
I just tried your `win2012r2x64` vagrantfile and all seems well. I had to use the `https://atlas.hashicorp.com/kensykora/boxes/windows_2012_r2_standard/versions/0.6.1/providers/virtualbox.box` box since the code did not reference a box.

But to be honest, I'm not sure what vagrant is supposed to look like when it "works" :D 
Should I be able to vagrant ssh into the windows box now? Or is Vagrant for windows strictly UI only?

**Comment by ferventcoder** [comment]
Depends on the box - my boxes have an sshd setup so you can ssh into the box. Not all do

**Comment by iDVB** [comment]
BTW, thanks again @ferventcoder !
Where should I go, place/community, to get additional Vagrant related support?
I've tried Gitter and it seems a bit empty for the most part.

**Comment by ferventcoder** [comment]
Freenode `#vagrant` is usually where I end up.

Or on https://github.com/mitchellh/vagrant

**Comment by iDVB** [comment]
Just a follow up. I've got `win2012r2x64` working the charm now. Everything seems to be working the charm and does not appear to be a victim of the issues described above. For me, this is perfect, since I've still a lot to learn.

**Comment by ferventcoder** [comment]
There is also this - https://github.com/mitchellh/vagrant/issues/5806 - it looks like you can specify the puppet binary path as well (maybe not until 1.7.3 though) - https://github.com/mitchellh/vagrant/issues/3740#issuecomment-115352085

**Comment by empi89** [comment]
With win2008r2x64-vagrant I had exactly the same issue (The `puppet` binary appears not to be in the PATH of the guest.) as described above when using vagrant 1.7.3. I updated vagrant to 1.7.4 and now the error has changed a bit:

==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: #< CLIXML
==> default: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">The term '$env:FACTER_domain=local' is not recognized as the name of a cmdlet, _x000D__x000A_</S><S S="Error">function, script file, or operable program. Check the spelling of the name, or _x000D__x000A_</S><S S="Error">if a path was included, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At line:1 char:28_x000D__x000A_</S><S S="Error">+ `$env:FACTER_domain='local' &lt;&lt;&lt;&lt; ; `$env:FACTER_kernel='windows'; `$env:FACTE_x000D__x000A_</S><S S="Error">R_operatingsystem='windows'; `$env:FACTER_osfamily='windows';  puppet apply --d_x000D__x000A_</S><S S="Error">ebug --trace --verbose --modulepath '/tmp/vagrant-puppet/modules-e2e621c2632735_x000D__x000A_</S><S S="Error">760f88669841cf5335;/ProgramData/PuppetLabs/puppet/etc/modules' --detailed-exitc_x000D__x000A_</S><S S="Error">odes --manifestdir /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5_x000D__x000A_</S><S S="Error">f3 /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/site.pp; exit_x000D__x000A_</S><S S="Error"> $LASTEXITCODE_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: ($env:FACTER_domain=local:String _x000D__x000A_</S><S S="Error">   ) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">The term '$env:FACTER_kernel=windows' is not recognized as the name of a cmdlet_x000D__x000A_</S><S S="Error">, function, script file, or operable program. Check the spelling of the name, o_x000D__x000A_</S><S S="Error">r if a path was included, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At line:1 char:59_x000D__x000A_</S><S S="Error">+ `$env:FACTER_domain='local'; `$env:FACTER_kernel='windows' &lt;&lt;&lt;&lt; ; `$env:FACTE_x000D__x000A_</S><S S="Error">R_operatingsystem='windows'; `$env:FACTER_osfamily='windows';  puppet apply --d_x000D__x000A_</S><S S="Error">ebug --trace --verbose --modulepath '/tmp/vagrant-puppet/modules-e2e621c2632735_x000D__x000A_</S><S S="Error">760f88669841cf5335;/ProgramData/PuppetLabs/puppet/etc/modules' --detailed-exitc_x000D__x000A_</S><S S="Error">odes --manifestdir /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5_x000D__x000A_</S><S S="Error">f3 /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/site.pp; exit_x000D__x000A_</S><S S="Error"> $LASTEXITCODE_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: ($env:FACTER_kernel=windows:Stri _x000D__x000A_</S><S S="Error">   ng) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">The term '$env:FACTER_operatingsystem=windows' is not recognized as the name of_x000D__x000A_</S><S S="Error"> a cmdlet, function, script file, or operable program. Check the spelling of th_x000D__x000A_</S><S S="Error">e name, or if a path was included, verify that the path is correct and try agai_x000D__x000A_</S><S S="Error">n._x000D__x000A_</S><S S="Error">At line:1 char:99_x000D__x000A_</S><S S="Error">+ `$env:FACTER_domain='local'; `$env:FACTER_kernel='windows'; `$env:FACTER_oper_x000D__x000A_</S><S S="Error">atingsystem='windows' &lt;&lt;&lt;&lt; ; `$env:FACTER_osfamily='windows';  puppet apply --d_x000D__x000A_</S><S S="Error">ebug --trace --verbose --modulepath '/tmp/vagrant-puppet/modules-e2e621c2632735_x000D__x000A_</S><S S="Error">760f88669841cf5335;/ProgramData/PuppetLabs/puppet/etc/modules' --detailed-exitc_x000D__x000A_</S><S S="Error">odes --manifestdir /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5_x000D__x000A_</S><S S="Error">f3 /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/site.pp; exit_x000D__x000A_</S><S S="Error"> $LASTEXITCODE_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: ($env:FACTER_operatingsystem=win _x000D__x000A_</S><S S="Error">   dows:String) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">The term '$env:FACTER_osfamily=windows' is not recognized as the name of a cmdl_x000D__x000A_</S><S S="Error">et, function, script file, or operable program. Check the spelling of the name,_x000D__x000A_</S><S S="Error"> or if a path was included, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At line:1 char:132_x000D__x000A_</S><S S="Error">+ `$env:FACTER_domain='local'; `$env:FACTER_kernel='windows'; `$env:FACTER_oper_x000D__x000A_</S><S S="Error">atingsystem='windows'; `$env:FACTER_osfamily='windows' &lt;&lt;&lt;&lt; ;  puppet apply --d_x000D__x000A_</S><S S="Error">ebug --trace --verbose --modulepath '/tmp/vagrant-puppet/modules-e2e621c2632735_x000D__x000A_</S><S S="Error">760f88669841cf5335;/ProgramData/PuppetLabs/puppet/etc/modules' --detailed-exitc_x000D__x000A_</S><S S="Error">odes --manifestdir /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5_x000D__x000A_</S><S S="Error">f3 /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/site.pp; exit_x000D__x000A_</S><S S="Error"> $LASTEXITCODE_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: ($env:FACTER_osfamily=windows:St _x000D__x000A_</S><S S="Error">   ring) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">The term 'puppet' is not recognized as the name of a cmdlet, function, script f_x000D__x000A_</S><S S="Error">ile, or operable program. Check the spelling of the name, or if a path was incl_x000D__x000A_</S><S S="Error">uded, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At line:1 char:141_x000D__x000A_</S><S S="Error">+ `$env:FACTER_domain='local'; `$env:FACTER_kernel='windows'; `$env:FACTER_oper_x000D__x000A_</S><S S="Error">atingsystem='windows'; `$env:FACTER_osfamily='windows';  puppet &lt;&lt;&lt;&lt;  apply --d_x000D__x000A_</S><S S="Error">ebug --trace --verbose --modulepath '/tmp/vagrant-puppet/modules-e2e621c2632735_x000D__x000A_</S><S S="Error">760f88669841cf5335;/ProgramData/PuppetLabs/puppet/etc/modules' --detailed-exitc_x000D__x000A_</S><S S="Error">odes --manifestdir /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5_x000D__x000A_</S><S S="Error">f3 /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/site.pp; exit_x000D__x000A_</S><S S="Error"> $LASTEXITCODE_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (puppet:String) [], CommandNotFo _x000D__x000A_</S><S S="Error">   undException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
136-083:win2008r2x64-vagrant ph$
