### ISSUE TITLE
Installing NodeJS on win2012r2x64 box

### ISSUE THREAD

**Issue by sahibjotsaggu** [ferventcoder/vagrant-windows-puppet#7]
I'm having difficulty installing NodeJS onto the 'win2012r2x64' box. There are no modules on puppet forge for nodejs that are compatible with Windows.. Is there any other way to install node?

**Comment by ferventcoder** [comment]
~~~puppet
package {'nodejs':
  ensure   => installed,
  provider => chocolatey,
}
~~~

Ensure you have chocolatey and the chocolatey provider installed.

**Comment by sahibjotsaggu** [comment]
I do have chocolatey installed but how do I know if the chocolatey provider is installed?

**Comment by ferventcoder** [comment]
`puppet module list`

**Comment by sahibjotsaggu** [comment]
I keep getting:
`Error: Permission denied - (C:/ProgramData/PuppetLabs/puppet/var/puppet-module/cache/chocolatey-chocolatey20150706-2372-
sea7bh, C:/ProgramData/PuppetLabs/puppet/etc/modules/chocolatey)
Error: Try 'puppet help module install' for usage`
whenever I do: `puppet module install chocolatey-chocolatey`

**Comment by sahibjotsaggu** [comment]
Solved!

**Comment by ferventcoder** [comment]
@sahibjotsaggu I'm guessing you figured out to do the module install from the host? Or it was already there?

**Comment by sahibjotsaggu** [comment]
@ferventcoder So in the Vagrantfile, there's this: 
`config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"`

I cloned chocolatey into a `chocolatey` folder inside puppet/box_modules.

This is my provision.pp (manifest_file):

```
case $operatingsystem {
  'windows':    {
    Package {
      provider => chocolatey,

    }
  }
}

# source   => 'C:\vagrant\resources\packages', isn't needed in the Package

package {'nodejs':
  ensure   => installed,
  provider => chocolatey,
}
```

**Comment by ferventcoder** [comment]
Awesome :)
