### ISSUE TITLE
Puppet With Chocolatey Provider

### ISSUE THREAD

**Issue by rholloway** [ferventcoder/vagrant-windows-puppet#8]
Hi there! Came across your windows Vagrant files here and thought I'd give it a shot as I need to get a windows dev environment up for a specific project. I'm pretty new to most of this Windows stuff as I usually stick to *nix, so bear with me if this question is n00b.

I am getting an error when trying to use puppet with the chocolatey provider. I just checked out your latest code and tried with both Win 7 and Win 2008 with same result. Note if I 'vagrant ssh' and then 'choco install poshgit' everything works fine - it's just when it's part of puppet that it breaks I suppose.

All I did was uncomment the install for poshgit via chocolatey in boxes/win2008r2x64-vagrant/puppet/manifests/site.pp.

  package {'poshgit':
   ensure => latest,
   provider => 'chocolatey',
   source => 'c:\vagrant\resources\packages;http://chocolatey.org/api/v2/',
 }

and re-ran vagrant provision. The result ends with

Error: Parameter provider failed on Package[poshgit]: Invalid package provider 'chocolatey' at C:/tmp/vagrant-puppet-4/manifests/site.pp:5
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:1849:in `block (2 levels) in providify'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/parameter.rb:465:in`validate'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/parameter.rb:500:in `value='
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:654:in`[]='
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:2272:in `block in set_parameters'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:2266:in`each'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:2266:in `set_parameters'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:2222:in`initialize'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource.rb:349:in `new'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource.rb:349:in`to_ral'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:524:in `block in to_catalog'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:516:in`each'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:516:in `to_catalog'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:408:in`to_ral'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/apply.rb:225:in `block in main'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/context.rb:64:in`override'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet.rb:244:in `override'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/apply.rb:198:in`main'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/apply.rb:159:in `run_command'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:381:in`block (2 levels) in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:507:in `plugin_hook'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:381:in`block in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:488:in `exit_on_fail'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:381:in`run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:146:in `run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:92:in`execute'
c:/Program Files/Puppet Labs/Puppet/puppet/bin/puppet:8:in `<main>'
An error occurred executing a remote WinRM command.

Shell: powershell
Command: $env:FACTER_domain='local'; $env:FACTER_kernel='windows'; $env:FACTER_operatingsystem='windows'; $env:FACTER_osfamily='windows';  puppet apply --debug --trace --verbose --modulepath '/ProgramData/PuppetLabs/puppet/etc/modules;/tmp/vagrant-puppet-4/modules-0' --manifestdir /tmp/vagrant-puppet-4/manifests --detailed-exitcodes /tmp/vagrant-puppet-4/manifests/site.pp
Message: Puppet failed with an exit code of 1

**Comment by rholloway** [comment]
Diving in a bit more, I'm trying to manually install rismoney-chocolatey module (or any module for that matter) by running 'puppet module install <modulename>' on the guest. However, it gives permission errors similar to seen at https://tickets.puppetlabs.com/browse/PUP-1827.

It seems with the Vagrantfile provided here, these scripts also use a synced folder for the base,

  config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"

Thus the default puppet module location is actually a share.

**Comment by ferventcoder** [comment]
Install from the host system. I have an example of what to pass in some of the boxes' puppet folders in the readme

**Comment by ferventcoder** [comment]
And that should be chocolatey-chocolatey. Which box is this?

**Comment by rholloway** [comment]
I was specifically referring to the Puppetfile for the Win7 box, but most Puppetfile's seem to reference rismoney (2003, 2008, etc).

Looking through the readme files, the only one that seems to have some extra content seems to be the microsoft-dsc box. It mentions navigating to the directory and running librarian-puppet (and does seem to refer to chocolatey-chocolatey in it's Puppetfile, so maybe most current?) Is that what you are referring to? If so, I guess that requires we have puppet and librarian-puppet installed on host? Or is that command meant to be run from the VM?

**Comment by ferventcoder** [comment]
That command is meant to be run from the host yes.

**Comment by ferventcoder** [comment]
I am going to close this as stale. I'm not sure if we came to a decision on this or if there is still an issue here. If there is, we can always reopen this.
