### ISSUE TITLE
baseboxes - link to drive

### ISSUE THREAD

**Issue by waldosCH** [ferventcoder/vagrant-windows-puppet#9]
Hello,
I tried your boxes that should help me a lot but...
The link to the gdrive seems to be broken...
If you would have the basebox for virtual box... it would be great.
thx.
Mathieu

**Comment by ferventcoder** [comment]
I'm not sure if all of them have been updated, but we have found some a home uploaded to vagrant cloud / atlas. Just search for my nickname there and switch the boxes to use those names. HTH
